server:
  port: 8094

spring:
  datasource:
    url: jdbc:mysql://plazoletaa.cdu3viw5kpiv.us-east-2.rds.amazonaws.com:3306/plazoletaa?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
